@Mind_Your_Drink_Server_LocalAddress = http://localhost:5161
@Mind_Your_Drink_Server_HostAddress = https://mind-your-drink-server20250611231310-h8aqf9a8cccgczfm.canadacentral-01.azurewebsites.net

### Create 5, 6
POST {{Mind_Your_Drink_Server_HostAddress}}/User/CreateAccount
Content-Type: application/json
Accept: application/json

{
  "Name": ",",
  "Password": ","
}

### Create 5, 6
POST {{Mind_Your_Drink_Server_HostAddress}}/User/CreateAccount
Content-Type: application/json
Accept: application/json

{
  "Name": "b",
  "Password": "b"
}

### Create Admin 7, 8
POST {{Mind_Your_Drink_Server_LocalAddress}}/Admin/CreateAdmin
Content-Type: application/json
Accept: application/json

{
  "Name": "adminhka",
  "Password": "admihnka"
}

### Ban 

POST {{Mind_Your_Drink_Server_LocalAddress}}/Admin/Ban
Content-Type: application/json
Accept: application/json

{
  "ToBanName": "7",
  "AdminPassword": "757b7d716be2b8c25fb166ff696b4d3de46b463592d7f96405a320d10cfb5660"
}


### Login Correct 1:2
POST {{Mind_Your_Drink_Server_LocalAddress}}/User/Login
Content-Type: application/json
Accept: application/json

{
  "Name": "adminka",
  "Password": "adminka"
}

### Login Correct 1:2
POST {{Mind_Your_Drink_Server_HostAddress}}/User/Login
Content-Type: application/json
Accept: application/json

{
  "Name": "adminka",
  "Password": "adminka"
}

### Login InCorrect 1:2
POST {{Mind_Your_Drink_Server_LocalAddress}}/User/Login
Content-Type: application/json
Accept: application/json

{
  "Name": "1",
  "Password": "3"
}

### Create 1.2  3, 4
POST {{Mind_Your_Drink_Server_HostAddress}}/User/CreateAccount
Content-Type: application/json
Accept: application/json

{
  "Name": "3",
  "Password": "4"
}

### Login 

POST {{Mind_Your_Drink_Server_HostAddress}}/User/Login
Content-Type: application/json
Accept: application/json

{
  "Name": "3",
  "Password": "4"
}

### Test Azure 

Get {{Mind_Your_Drink_Server_HostAddress}}/Test/ping
Content-Type: application/json
Accept: application/json

### User Drink Test
POST {{Mind_Your_Drink_Server_HostAddress}}/UserDrink/CreateUserDrink
Content-Type: application/json
Accept: application/json

{
  "name": "vik",
  "hash": "3bc508d48b0c83ec09d4230985d0b36d432dd3cc432b1192ffb9b9d0b6759418",
  "userDrink": {
    "id": 0,
    "userId": 0,
    "name": "Whiskey",
    "type": 1,
    "abv": 40,
    "callories": 250,
    "price": 5.99,
    "volumeInMl": 50,
    "time": "2025-06-14T08:00:00Z"
  }
}

### GetAllDrinks Test
POST {{Mind_Your_Drink_Server_HostAddress}}/UserDrink/GetAllDrinks
Content-Type: application/json
Accept: application/json

{

  "name": "k"

}

### GetAllDrinks Test
 POST {{Mind_Your_Drink_Server_HostAddress}}/UserDrink/GetAllDrinks
Content-Type: application/json
Accept: application/json

{
  "name": "k"
}

### GetAllDrinks Test
 POST {{Mind_Your_Drink_Server_LocalAddress}}/Admin/GetAllUserInfo
Content-Type: application/json
Accept: application/json

{
  "Name": "adminka",
  "Password": "757b7d716be2b8c25fb166ff696b4d3de46b463592d7f96405a320d10cfb5660"
}

### Get all info about user Test
 POST {{Mind_Your_Drink_Server_HostAddress}}/Admin/GetAllUserInfo
Content-Type: application/json
Accept: application/json

{
  "Name": "adminka",
  "Password": "757b7d716be2b8c25fb166ff696b4d3de46b463592d7f96405a320d10cfb5660"

}

### Lox

 POST {{Mind_Your_Drink_Server_HostAddress}}/Admin/GetAllUserInfo
Content-Type: application/json
Accept: application/json

{
  "Name": "adminka",
  "Password": "757b7d716be2b8c25fb166ff696b4d3de46b463592d7f96405a320d10cfb5660"
}

### Get all Drinks by date
POST {{Mind_Your_Drink_Server_HostAddress}}/UserDrink/GetDrinksByDay
Content-Type: application/json
Accept: application/json

{
  "Name": "kk",
  "Date": "2025-06-15T22:35:01.0618986"
}

### GetAllDrinks Test
POST {{Mind_Your_Drink_Server_HostAddress}}/UserDrink/GetAllDrinks
Content-Type: application/json
Accept: application/json

{

  "name": "kk"

}

### User Drink Test
POST {{Mind_Your_Drink_Server_HostAddress}}/UserDrink/CreateUserDrink
Content-Type: application/json
Accept: application/json

{
  "name": "k",
  "hash": "8254c329a92850f6d539dd376f4816ee2764517da5e0235514af433164480d7a",
  "userDrink": {
    "id": 0,
    "userId": 0,
    "name": "Whiskey",
    "type": 1,
    "abv": 40,
    "calories": 250,
    "price": 5.99,
    "volumeInMl": 50,
    "time": "2025-06-15T00:00:00",
    "icon": "gg.png"
  }
}

### User Drink Test
POST {{Mind_Your_Drink_Server_LocalAddress}}/UserDrink/CreateUserDrink
Content-Type: application/json
Accept: application/json

{
  "name": "k",
  "hash": "8254c329a92850f6d539dd376f4816ee2764517da5e0235514af433164480d7a",
  "userDrink": {
    "id": 0,
    "userId": 0,
    "name": "Whiskey",
    "type": 1,
    "abv": 40,
    "calories": 250,
    "price": 5.99,
    "volumeInMl": 50,
    "time": "2025-06-15T00:00:00",
    "icon": "gg.png"
  }
}